### ISSUE TITLE
Report ENOTDIR spawnSync /usr/bin/env/swiftformat ENOTDIR

### ISSUE THREAD

**Issue by Qusea** [vknabel/vscode-swiftformat#22]
`Error: spawnSync /usr/bin/env/swiftformat ENOTDIR
    at Object.spawnSync (node:internal/child_process:1111:20)
    at spawnSync (node:child_process:834:24)
    at Object.execFileSync (node:child_process:880:15)
    at Object.func [as execFileSync] (node:electron/js2c/asar_bundle:5:1812)
    at format (/Users/quseasaif/.vscode/extensions/vknabel.vscode-swiftformat-1.6.2/out/src/SwiftFormatEditProvider.js:54:40)
    at SwiftFormatEditProvider.provideDocumentFormattingEdits (/Users/quseasaif/.vscode/extensions/vknabel.vscode-swiftformat-1.6.2/out/src/SwiftFormatEditProvider.js:85:16)
    at $.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:39761)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:61932
    at le.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:56737)
    at le.$provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:61919)
    at l.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:11239)
    at l.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10957)
    at l.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10005)
    at l.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:9022)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:7810
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:15815
    at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:13941)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)`

**Comment by vknabel** [comment]
Hi @Qusea, thanks for your report. Do you remember when you experienced this error?
It seems some directory didn't exist (anymore).

**Comment by Qusea** [comment]
Not really, it's possible the error occurred after I uninstalled Xcode.

**Comment by vknabel** [comment]
That could be the case, although it should produce a different error message.
I have a few guesses I'll try. Though it might take some time to validate.
