### ISSUE TITLE
Report  Command failed: /usr/local/bin/swift-format stdin --stdinpath /Users/quseasaif/Documents/Code/xcode/Little Lemon/Little Lemon/Menu.swift --indent 2Error: Unknown option '--stdinpath'Usage: swift-format format [--in-place] [--configuration <configuration>] [--assume-filename <assume-filename>] [--recursive] [--ignore-unparsable-files] [--parallel] [--color-diagnostics] [--no-color-diagnostics] [<paths> ...]  See 'swift-format format --help' for more information.

### ISSUE THREAD

**Issue by Qusea** [vknabel/vscode-swiftformat#31]
`Error: Command failed: /usr/local/bin/swift-format stdin --stdinpath /Users/quseasaif/Documents/Code/xcode/Little Lemon/Little Lemon/Menu.swift --indent 2
Error: Unknown option '--stdinpath'
Usage: swift-format format [--in-place] [--configuration <configuration>] [--assume-filename <assume-filename>] [--recursive] [--ignore-unparsable-files] [--parallel] [--color-diagnostics] [--no-color-diagnostics] [<paths> ...]
  See 'swift-format format --help' for more information.

    at checkExecSyncError (node:child_process:945:11)
    at execFileSync (node:child_process:981:15)
    at func (node:electron/js2c/asar_bundle:2:1869)
    at execShellSync (/Users/quseasaif/.vscode/extensions/vknabel.vscode-swiftformat-1.6.7/out/src/execShell.js:15:49)
    at format (/Users/quseasaif/.vscode/extensions/vknabel.vscode-swiftformat-1.6.7/out/src/SwiftFormatEditProvider.js:56:59)
    at SwiftFormatEditProvider.provideDocumentFormattingEdits (/Users/quseasaif/.vscode/extensions/vknabel.vscode-swiftformat-1.6.7/out/src/SwiftFormatEditProvider.js:89:16)
    at O.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:45401)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:68987
    at be.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:63736)
    at be.$provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:68976)
    at i.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10827)
    at i.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10593)
    at i.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:9645)
    at i.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:8762)
    at s.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:7565)
    at c.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at m.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14010)
    at s.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:7902)
    at c.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at m.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14010)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:6182)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)`

**Comment by vknabel** [comment]
Hi @Qusea,

It seems like you try to run https://github.com/apple/swift-format (according to the dash) using the wrong extension.

`swiftformat` is Nick Lockwood's https://github.com/nicklockwood/SwiftFormat. Then use this extension https://github.com/vknabel/vscode-swiftformat.

You currently have installed `swift-format` by apple https://github.com/apple/swift-format. Use the other extension https://github.com/vknabel/vscode-apple-swift-format
