### ISSUE TITLE
Report  /usr/bin/env failed with exit code 1.

### ISSUE THREAD

**Issue by AgustinTommasi** [vknabel/vscode-swiftformat#51]
`Error: /usr/bin/env failed with exit code 1.
	at execShellSync (c:\Users\Agustin\.vscode\extensions\vknabel.vscode-swiftformat-1.6.10\out\src\execShell.js:13:19)
	at format (c:\Users\Agustin\.vscode\extensions\vknabel.vscode-swiftformat-1.6.10\out\src\SwiftFormatEditProvider.js:56:59)
	at SwiftFormatEditProvider.provideDocumentFormattingEdits (c:\Users\Agustin\.vscode\extensions\vknabel.vscode-swiftformat-1.6.10\out\src\SwiftFormatEditProvider.js:89:16)
	at W.provideDocumentFormattingEdits (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:109715)
	at c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:138677
	at De.s (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:133052)
	at De.$provideDocumentFormattingEdits (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:138664)
	at E.S (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5980)
	at E.Q (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5746)
	at E.M (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4739)
	at E.L (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:3605)
	at i.value (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:2297)
	at n.B (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.fire (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
	at s.fire (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
	at i.value (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:8655)
	at n.B (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.fire (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
	at s.fire (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
	at MessagePortMain.<anonymous> (c:\Users\Agustin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6781)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)`

**Comment by vknabel** [comment]
As I currently neither use Swift nor VS Code, I‘d be happy to receive a PR.
